name: CI
on: [push, pull_request]
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.13.1]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        run: yarn
      - name: Lint
        run: yarn lint
      - name: Test
        run: CI=true yarn test
      - name: Build
        run: yarn build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
  lighthouse-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: yarn
      - name: Run Lighthouse
        uses: foo-software/lighthouse-check-action@master
        id: lighthouseCheck
        with:
          urls: 'https://olivermicke.github.io/monthly-budget-planner/#/calendar,https://olivermicke.github.io/monthly-budget-planner/#/transactions'
      - name: Handle Lighthouse Check results
        uses: foo-software/lighthouse-check-status-action@master
        with:
          minAccessibilityScore: '100'
          minBestPracticesScore: '80'
          minPerformanceScore: '50'
          minProgressiveWebAppScore: '50'
          minSeoScore: '90'
